server.port=8080
spring.application.name=badwallet-api
spring.datasource.url=jdbc:h2:mem:badwalletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5